import React from "react";

export let Data: ({ technologies: string; collaboration: string; name: string; details: string; media: string; url: string, done: boolean })[] = [
    {
        "name": "Portfolio",
        "url": "https://github.com/Lsimelus/Portfolio",
        "collaboration": "None",
        "details": "asdas",
        "technologies":"React, TypeScript, Styled Css, PostgressSQL, Java,",
        "media": "",
        "done": false,
    },
    {
        "name": "RoyalFitness",
        "url": "https://github.com/Lsimelus/RoyalFitness",
        "collaboration": "Partner(s)",
        "details": "sadsad",
        "technologies":"Swift, Google Console Firebase",
        "media": "",
        "done": false,
    },
    {
        "name": "Casual Creator",
        "url": "https://github.com/Lsimelus/CasualCreator",
        "collaboration": "None",
        "details": "Colored blocks enables the user to enjoy the dearly missed satisfaction of playing with blocks without the mess. To run the code all the user has to do is click the mouse and shapes appear wherever the mouse is clicked. By pressing any of the 4 arrow keys, shift, enter, and alt, change the blocks.",
        "technologies":"ProcessingJ",
        "media": "https://drive.google.com/drive/folders/1oe3GCQM7PS5JahcN47YT9l9wF1ctIgm9?usp=sharing",
        "done": true,
    },
    {
        "name": "Poem Generator",
        "url": "https://github.com/Lsimelus/Poetry-Generator",
        "collaboration": "Partner(s)",
        "details": "A system that successfully creates rhyming and reasonably coherent poems by reading a sample of poems. The poems can be themed after a certain poet if selected.",
        "technologies":"Pyhton",
        "media": "",
        "done": false,
    },
    {
        "name": "Cookie Recipe Generator",
        "url": "https://github.com/Lsimelus/Cookie-Recipe-Generator",
        "collaboration": "Partner(s)",
        "details": "Using flavorDB, I along with two of my classmates created a system that successfully generates novel and unique cookie recipes by looking at their molecular similarities. The molecular makeup of these molecules was found via. https://cosylab.iiitd.edu.in/flavordb/. ",
        "technologies":"Python",
        "media": "",
        "done": false,
    },
    {
        "name": "Fake news generator",
        "url": "https://github.com/Lsimelus/Not-So-Legitimate-News",
        "collaboration": "None",
        "details": "System that generates \"Not so Legitimate News\". Visuals are included using Javax",
        "technologies":"Java",
        "media": "https://drive.google.com/drive/folders/13fz1aZ538SXqc0kpMwP6J0BEIBM-oSr1?usp=sharing",
        "done": true,
    },
    {
        "name": "Ruby beat",
        "url": "https://github.com/Lsimelus/RubyBeat",
        "collaboration": "none",
        "details": "A beat I made using ruby",
        "technologies":"Sonic Pi, Ruby",
        "media": "https://drive.google.com/drive/folders/1ODtwUAg9vctABen1ZMk_gmQlg-ZdM-3r?usp=sharing",
        "done": true,
    },
    {
        "name": "Sample Site",
        "url": "https://github.com/Lsimelus/Non-interactiveWebsite",
        "collaboration": "Partner(s)",
        "details": "Basic website created showing my ability to use HTML and Css",
        "technologies":"Html, Bootstrap",
        "media": "https://lsimelus.github.io/Non-interactiveWebsite/",
        "done": true,
    },
    {
        "name": "Sample Site2",
        "url": "https://github.com/Lsimelus/Non-InteractiveWebsite2",
        "collaboration": "Partner(s)",
        "details": "Basic website created showing my ability to use HTML and Css",
        "technologies":"Html, Css, Javascript",
        "media": "https://lsimelus.github.io/Non-InteractiveWebsite2/",
        "done": true,
    },
    {
        "name": "Neural Networks",
        "url": "https://github.com/Lsimelus/NeuralNetworks2",
        "collaboration": "None",
        "details": "See how neural networks reform with varying sample sizes perform",
        "technologies":"Java",
        "media": "",
        "done": false,
    },
    {
        "name": "Genetic Algorithm",
        "url": "https://github.com/Lsimelus/GeneticAlgorithm",
        "collaboration": "None",
        "details": "Using Genetic Algorithm find a key string from a string of random characters. Various Genetic Algorithm methods implemented and can be used with minor edits in the code.",
        "technologies":"Java",
        "media": "",
        "done": false,
    },
    {
        "name": "Markov Decision Process",
        "url": "https://github.com/Lsimelus/MarkovDecisionProcess",
        "collaboration": "None",
        "details": "Demonstrates the effectiveness of the Markov decision precess. Ran through the terminal with varying commands of 'java SmallGrid 0.99 1e-6 1 -1 -0.04'",
        "technologies":"Java",
        "media": "",
        "done": true,
    }
];
export default Data;